baseURL = "/NCTU_ICT_Embedded_System/"
languageCode = "zh-tw"
title = "交通"

theme = "hugo-theme-learn"
googleAnalytics = "UA-167313793-2"

DefaultContentLanguage = "tw"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    themeVariant = "blue"



[Languages]

[Languages.tw]
title = "國立交通大學, 嵌入式作業系統設計與實作"
weight = 1
languageName = "繁體中文"

[Languages.en]
title = "NCTU, EOSDI"
weight = 2
languageName = "English"
